fix the missing json import
Fix the NameError when running pvacvector

```
Traceback (most recent call last):
  File "/usr/local/bin/pvacvector", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacvector/main.py", line 50, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacvector/run.py", line 467, in main
    input_file = shorten_problematic_peptides(input_file, problematic_start, problematic_end, os.path.join(base_output_dir, str(tries)))
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacvector/run.py", line 335, in shorten_problematic_peptides
    record_new = SeqRecord(Seq(str(record.seq)[1:], IUPAC.protein), id=record.id, description=json.dumps({'problematic_start': True, 'problematic_end': False}))
NameError: name 'json' is not defined
```